# Generated by Django 3.2.9 on 2022-07-18 11:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_file', models.FileField(default='media/test1.pdf', upload_to='media/')),
                ('title', models.CharField(default='Unknown title', max_length=50)),
                ('screened_by_username', models.CharField(default='None', max_length=50)),
                ('is_screened', models.BooleanField(default=False)),
                ('relevancy', models.IntegerField(default=2)),
                ('score', models.FloatField(default=0.0)),
                ('added_on', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_username', models.CharField(default='temp_username', max_length=50)),
                ('role', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('profile_pic', models.FileField(default='images/avatar2.png', upload_to='images/')),
                ('banner_pic', models.FileField(default='images/banner1.jpg', upload_to='images/')),
                ('documents_screened', models.IntegerField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('history_enabled', models.BooleanField(default=True)),
                ('is_classified', models.BooleanField(default=False)),
                ('recall_list', models.CharField(default='', max_length=500000)),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workbench.profile')),
            ],
        ),
        migrations.CreateModel(
            name='TempRIS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_file', models.FileField(default='media/test1.pdf', upload_to='media/')),
                ('review_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workbench.review')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50)),
                ('review_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workbench.review')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('documents_screened', models.IntegerField(default=0)),
                ('review_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workbench.review')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('type', models.CharField(max_length=50)),
                ('created_by', models.CharField(default='temp_username', max_length=50)),
                ('review_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workbench.review')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('type', models.CharField(max_length=50)),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workbench.profile')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workbench.document')),
                ('tag_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workbench.tag')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentRIS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='(Unknown title)', max_length=50)),
                ('abstract', models.CharField(default='(Unavailable)', max_length=50)),
                ('doc_id', models.CharField(default='(Unavailable)', max_length=50)),
                ('screened_by_username', models.CharField(default='None', max_length=50)),
                ('is_screened', models.BooleanField(default=False)),
                ('relevancy', models.IntegerField(default=2)),
                ('score', models.FloatField(default=0.0)),
                ('added_on', models.DateTimeField(default=datetime.datetime.now)),
                ('review_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workbench.review')),
                ('screened_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='screened_by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='review_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workbench.review'),
        ),
        migrations.AddField(
            model_name='document',
            name='screened_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='screened_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
